default:
	sqlplus jhodgson/qwer1234 @setup_new.sql
	sqlplus jhodgson/qwer1234 @table_updates.sql
	sqlplus jhodgson/qwer1234 @views.sql
	sqlplus jhodgson/qwer1234 @inverted_index.sql
	sqlplus jhodgson/qwer1234 @admin.sql
	
dev:
	sqlplus jhodgson/qwer1234 @setup_new.sql
	sqlplus jhodgson/qwer1234 @table_updates.sql
	sqlplus jhodgson/qwer1234 @views.sql
	sqlplus jhodgson/qwer1234 @inverted_index.sql
	sqlplus jhodgson/qwer1234 @admin.sql
	sqlplus jhodgson/qwer1234 @table_data.sql
